spring:
  main:
    web-application-type: none
  cloud:
    function:
      definition: receiveGreeting;receiveTime
    stream:
      bindings:
        receiveGreeting-in-0:
          destination: decoratedChannel
        receiveTime-in-0:
          destination: timeChannel
          group: second
